# permissions for end users to view apitests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apitest-viewer-role
rules:
- apiGroups:
  - test.yildizozan.com
  resources:
  - apitests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.yildizozan.com
  resources:
  - apitests/status
  verbs:
  - get
